name: GHA-frac-Release

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install gtest manually
      run: |
        sudo apt-get install libgtest-dev libgmock-dev
        cd /usr/src/gtest 
        sudo cmake CMakeLists.txt 
        sudo make && ls -l lib 
        sudo cp lib/*.a /usr/lib 
        sudo ln -s /usr/lib/libgtest.a /usr/local/lib/libgtest.a
        sudo ln -s /usr/lib/libgtest_main.a /usr/local/lib/libgtest_main.a
    - uses: actions/checkout@v1
    - name: configure
      run: mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS="-Werror" ..
    - name: make
      run: cd build && make
    - name: Run Test
      run: |
        export REPO_NAME=${GITHUB_REPOSITORY#$GITHUB_REPOSITORY_OWNER/}
        /home/runner/work/${REPO_NAME}/${REPO_NAME}/build/test/ST-3.test
